apiVersion: batch/v1
kind: Job
metadata:
  name: sidecar-test
spec:
  template:
    spec:
      shareProcessNamespace: true
      restartPolicy: Never
      containers:
        - name: main
          image: main:latest
          imagePullPolicy: Never
      initContainers:
        - name: sidecar
          image: sidecar:latest
          imagePullPolicy: Never
          restartPolicy: Always
          ports:
            - name: http
              containerPort: 8080
          startupProbe:
            httpGet:
              path: /
              port: 8080
            initialDelaySeconds: 5
            periodSeconds: 5
            failureThreshold: 10
          readinessProbe:
            httpGet:
              path: /
              port: 8080
            initialDelaySeconds: 5
            periodSeconds: 5
