apiVersion: batch/v1
kind: Job
metadata:
  name: sidecar-test
spec:
  template:
    spec:
      restartPolicy: Never
      containers:
        - name: main
          image: main:latest
          imagePullPolicy: Never
      initContainers:
        - name: sidecar1
          image: sidecar:latest
          imagePullPolicy: Never
          restartPolicy: Always
          env:
            - name: PORT
              value: "8081"
          ports:
            - name: http
              containerPort: 8081
          startupProbe:
            httpGet:
              path: /
              port: 8081
            initialDelaySeconds: 5
            periodSeconds: 5
            failureThreshold: 10
        - name: sidecar2
          image: sidecar:latest
          imagePullPolicy: Never
          restartPolicy: Always
          ports:
            - name: http
              containerPort: 8080
          startupProbe:
            httpGet:
              path: /
              port: 8080
            initialDelaySeconds: 5
            periodSeconds: 5
            failureThreshold: 10
